### ISSUE TITLE
Hardhat: Error when calling Smart Contract's method from signer other then deployer 

### ISSUE THREAD

**Issue by Formator** [oasisprotocol/sapphire-paratime#123]
I'm getting an error if I call the normal Smart Contract method from the signer that is not the original smart contract deployer.

For easy issue replication, I have prepared [repo](https://github.com/Formator/sapphire-hardhat-state-issue). Issue can be discovered if you run the script test.js on **Sapphire TestNet**.

Inside test.js script you can find the line:
```javascript
let testerTokenBalanceBefore = await testerTokenReadInstance.balanceOf(
    tester.address
  );
```

On this line I'm getting the error:
```console
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0xC88309139e5809f4E736D700bB8Aca31540C67d8","to":"0x29512C25ac8d5bE86FD83bee380EDAc5a726947C","data":"0x70a08231000000000000000000000000c88309139e5809f4e736d700bb8aca31540c67d8","accessList":null}, error={"name":"ProviderError","_stack":"ProviderError: invalid signed simulate call query: signer != caller\n    at HttpProvider.request ...
```

Testing on my side has been done with last source version of @oasisprotocol/sapphire-hardhat.

**Comment by xmzheng** [comment]
Hi @Formator I cannot reproduce your problem. I tested your script locally and can get the correct result:
```
2 - Check if tester account has at least 100 tokens if he has't, send them from deployer account
Deployer account token balance before transfer: 1000000
Tester account token balance before transfer: 0
before transaction
transaction completed
Deployer account token balance after transfer: 999900
Tester account token balance after transfer: 100
3 - Check if tester account can transfer 10 token to deployer account
Deployer account token balance before transfer: 999900
Tester account token balance before transfer: 100
Deployer account token balance after transfer: 999910
Tester account token balance after transfer: 90

```

**Comment by xmzheng** [comment]
remembered that I removed the wrap statement in hardhat integration in this [line](https://github.com/oasisprotocol/sapphire-paratime/blob/main/integrations/hardhat/src/index.ts#L24)

**Comment by Formator** [comment]
@xmzheng 
 > remembered that I removed the wrap statement in hardhat integration in this [line](https://github.com/oasisprotocol/sapphire-paratime/blob/main/integrations/hardhat/src/index.ts#L24)

If I understand correctly, you have removed [line](https://github.com/oasisprotocol/sapphire-paratime/blob/main/integrations/hardhat/src/index.ts#L24) on your local sources, re-run the test, and couldn't reproduce my problem.

If I do the same, I also kind of solve problems with this issue but get error on `transfer`, so I couldn't reproduce your output, did you run test on sapphire testnet?

```console
ProviderError: query aborted: Any { .. }
    at HttpProvider.request (/../sapphire-hardhat-state-issue/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (/../sapphire-hardhat-state-issue/lib/internal/process/task_queues.js:96:5)
    at EthersProviderWrapper.send (/../sapphire-hardhat-state-issue/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20) {parent: undefined, name: 'ProviderError', _stack: 'ProviderError: query aborted: Any { .. }
    …c/internal/ethers-provider-wrapper.ts:13:20)', code: -32000, _isProviderError: true, …}
```

**Comment by xmzheng** [comment]
I pushed my code to branch `xmzheng/sapphire`, both deploy.js and test.js works fine.

```
Deploying the contracts with the account: 0xfA3AC9f65C9D75EE3978ab76c6a1105f03156204
Account balance: 9721230200000000000
Token address: 0x85140939DD2Ee1C2156507daEaDF82FE66a254F3
```

```
Token address: 0x85140939DD2Ee1C2156507daEaDF82FE66a254F3
Token deployer was:  0xfA3AC9f65C9D75EE3978ab76c6a1105f03156204
Testing the contracts with the account: 0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65
1 - Check if tester account has enough ether
Tester account balance: 9487413500000000000
2 - Check if tester account has at least 100 tokens if he has't, send them from deployer account
Deployer account token balance before transfer: 1000000
Tester account token balance before transfer: 0
before transaction
transaction completed
Deployer account token balance after transfer: 999900
Tester account token balance after transfer: 100
3 - Check if tester account can transfer 10 token to deployer account
Deployer account token balance before transfer: 999900
Tester account token balance before transfer: 100
Deployer account token balance after transfer: 999910
Tester account token balance after transfer: 90
```

**Comment by Formator** [comment]
@xmzheng Interesting, It's working now. Thank you!
