### ISSUE TITLE
Sapphire JS compatibility library issue with Truffle callback

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/sapphire-paratime#127]
#### Reproduction

Using the latest version of `Truffle v5.8.2 (core: 5.8.2)` with the documented steps for a Sapphire dApp runs into an issue with the JS compatibility library.

```
UnhandledRejections detected
Promise {
  <rejected> TypeError: callback is not a function
      at /Users/xi/.npm/_npx/7be3639a7343b447/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:165:1
      at /Users/xi/oasis/MetaCoin/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:399:2
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
} TypeError: callback is not a function
    at /Users/xi/.npm/_npx/7be3639a7343b447/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:165:1
    at /Users/xi/oasis/MetaCoin/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:399:2
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Promise {
  <rejected> TypeError: callback is not a function
      at /Users/xi/.npm/_npx/7be3639a7343b447/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:165:1
      at /Users/xi/oasis/MetaCoin/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:399:2
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
} TypeError: callback is not a function
    at /Users/xi/.npm/_npx/7be3639a7343b447/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:165:1
    at /Users/xi/oasis/MetaCoin/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:399:2
```

**Comment by CedarMist** [comment]
This is still present with 5.10.1.

Having a look into it.

```
UnhandledRejections detected
Promise {
  <rejected> TypeError: callback is not a function
      at /src/sapphire-quickstart/node_modules/.pnpm/truffle@5.10.1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:166:1
      at /src/sapphire-quickstart/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:397:23
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
} TypeError: callback is not a function
    at /src/sapphire-quickstart/node_modules/.pnpm/truffle@5.10.1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:166:1
    at /src/sapphire-quickstart/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:397:23
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Promise {
  <rejected> TypeError: callback is not a function
      at /src/sapphire-quickstart/node_modules/.pnpm/truffle@5.10.1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:166:1
      at /src/sapphire-quickstart/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:397:23
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
} TypeError: callback is not a function
    at /src/sapphire-quickstart/node_modules/.pnpm/truffle@5.10.1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:166:1
    at /src/sapphire-quickstart/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:397:23
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by lukaw3d** [comment]
Debugging on "Uncaught Exception" I get the following issue sites:

`send(payload, callback). callback = undefined`
https://github.com/oasisprotocol/sapphire-paratime/blob/9a74e57e72b06ba86ec8454062b8c0a5281edb97/clients/js/src/compat.ts#L217

`args = undefined`
https://github.com/oasisprotocol/sapphire-paratime/blob/9a74e57e72b06ba86ec8454062b8c0a5281edb97/clients/js/src/compat.ts#L368

`send(payload, callback). callback = []`
https://github.com/oasisprotocol/sapphire-paratime/blob/9a74e57e72b06ba86ec8454062b8c0a5281edb97/clients/js/src/compat.ts#L517

**Comment by CedarMist** [comment]
Yup, managed to get this:
```
Exception has occurred: TypeError: Cannot read properties of undefined (reading 'method')
  at /src/sapphire-quickstart/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:368:14
    at Generator.next (<anonymous>)
    at /src/sapphire-quickstart/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/lib/cjs/compat.cjs:31:71
    at new Promise (<anonymous>)
    at __awaiter (/src/sapphire-quickstart/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/lib/cjs/compat.cjs:27:12)
    at /src/sapphire-quickstart/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:367:38
    at Proxy.<anonymous> (/src/sapphire-quickstart/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:395:5)
    at /src/sapphire-quickstart/node_modules/.pnpm/@truffle+provider@0.3.10/node_modules/@truffle/provider/wrapper.js:160:7
    at isEthersSend (/src/sapphire-quickstart/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:217:18)
    at makeWeb3Provider (/src/sapphire-quickstart/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:539:29)
    at /src/sapphire-quickstart/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/src/compat.ts:531:20
    at Generator.next (<anonymous>)
    at fulfilled (/src/sapphire-quickstart/node_modules/.pnpm/@oasisprotocol+sapphire-paratime@1.0.15/node_modules/@oasisprotocol/sapphire-paratime/lib/cjs/compat.cjs:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by CedarMist** [comment]
Returning `false` from `isEthersSigner` removes one error, ideally there should be a better check for it as the current check is super hacky.

The other error that remains is via `fetchRuntimePublicKey` seems to be called via:

```javascript
const { key } = yield source.send(index_js_1.OASIS_CALL_DATA_PUBLIC_KEY, []);
```

Which passes empty array as 2nd parameter.

This violates Web3 HttpProvider API: https://docs.web3js.org/api/web3-providers-http/class/HttpProvider#send

**Comment by CedarMist** [comment]
I have committed a fix and added multiple versions of Truffle to the testing matrix, so we know it works with them in addition to Hardhat.

Need to review the versions used as dependencies in `packages.json` and schedule weekly build with whatever the latest version is of Truffle & Hardhat rather than locking the version in `.lock` files.
