### ISSUE TITLE
Incompatibility with Hardhat 2.16.1

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/sapphire-paratime#143]
When using Hardhat 2.16.1 there's an error in `extendEnvironment`.

The customized fork of hardhat is based on 2.12.6.

```
> hardhat-boilerplate@1.0.0 test /home/runner/work/sapphire-paratime/sapphire-paratime/examples/hardhat-boilerplate
> hardhat test

An unexpected error occurred:

TypeError: Cannot read properties of undefined (reading 'add')
    at extendEnvironment (/home/runner/work/sapphire-paratime/sapphire-paratime/node_modules/.pnpm/hardhat@2.12.6_qkpo4aptcl5wogwco44qzoggoq/node_modules/hardhat/src/internal/core/config/config-env.ts:130:19)
    at Object.<anonymous> (/home/runner/work/sapphire-paratime/sapphire-paratime/integrations/hardhat/src/index.ts:8:18)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/runner/work/sapphire-paratime/sapphire-paratime/examples/hardhat-boilerplate/hardhat.config.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
```

Snippet from `config-env.ts` in oasislabs 2.12.6 fork:
https://github.com/oasislabs/hardhat/blob/6bf1a3de107b841c737df834da2ba366b5b3e390/packages/hardhat-core/src/internal/core/config/config-env.ts#L127C1-L131

```typescript
export function extendEnvironment(extender: EnvironmentExtender) {
  const ctx = HardhatContext.getHardhatContext();
  const extenderManager = ctx.extendersManager;
  extenderManager.add(extender);
}
```

However in 2.16.x the internal implementation is different:
https://github.com/NomicFoundation/hardhat/blob/6779768011cd9a97973c57d6d27ad4e8a49b7d58/packages/hardhat-core/src/internal/core/config/config-env.ts#L128-L131

```typescript
export function extendEnvironment(extender: EnvironmentExtender) {
  const ctx = HardhatContext.getHardhatContext();
  ctx.environmentExtenders.push(extender);
}
```

As in, there are is confusion internally where 2.12.6 code is calling 2.16.x code, which isn't ideal.

------

Various versions of hardhat can be added into the testing matrix, as per: 

https://github.com/oasisprotocol/sapphire-paratime/pull/142/commits/627b9db488a94e7018b115712753e2490109ee2c

**Comment by CedarMist** [comment]
Fixed by #144
