### ISSUE TITLE
client/js: Occasional error: TypeError: Cannot read properties of undefined (reading 'key')

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/sapphire-paratime#147]
This happened when merging from a branch into main.

The tests completed OK on the branch, but after merging into main it fails.

See: https://github.com/oasisprotocol/sapphire-paratime/actions/runs/5465401574/attempts/1

The second attempt succeeds.

Maybe it's worth re-trying the fetch runtime public key function? Or having some other way of safely erroring.

```
     TypeError: Cannot read properties of undefined (reading 'key')
      at /home/runner/work/sapphire-paratime/sapphire-paratime/clients/js/src/cipher.ts:294:30
      at Generator.next (<anonymous>)
      at fulfilled (/home/runner/work/sapphire-paratime/sapphire-paratime/clients/js/lib/cjs/cipher.cjs:28:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by lukaw3d** [comment]
Does this ever happen outside tests? My first thought would be that waiting for containers to initialize is inaccurate

**Comment by CedarMist** [comment]
Yup it does, I encounter it sometimes in the browser when using sapphire-dev, but haven't narrowed down exactly what happens. The worst thing is it's intermittent.
