### ISSUE TITLE
Vigil example doesn't work with docker dev network

### ISSUE THREAD

**Issue by jaa2** [oasisprotocol/sapphire-paratime#188]
##### SUMMARY

The [Vigil example contract](https://docs.oasis.io/dapp/sapphire/quickstart/#create-a-sapphire-native-dapp) doesn't run correctly in a [private dev network](https://docs.oasis.io/dapp/sapphire/guide/#running-a-private-oasis-network-locally). Specifically, the `revealSecret` transaction fails, and there doesn't seem to be an indication of what went wrong.

I came across this issue intending to create a way to reproduce a separate issue where I am getting a `ProviderError: invalid signed simulate call query: signer != caller` error in a similar dev network setup when trying to make contract calls from a signer that did not create the contract. That might be related to #123 and #125 .

##### ISSUE TYPE
- Bug Report

##### STEPS TO REPRODUCE

1. Follow the "Create a Sapphire-Native dApp" instructions.
2. Add a dev entry to the networks object in `hardhat.config.ts`:
```ts
    dev: {
      url: 'http://127.0.0.1:8545',
      accounts: process.env.PRIVATE_KEY
        ? [process.env.PRIVATE_KEY]
        : [],
      chainId: 0x5A_FD,
    },
```
3. Run the local private development network:
```sh
docker run -it -p8545:8545 -p8546:8546 ghcr.io/oasisprotocol/sapphire-dev -to "0xBe939A55A64e20a198522DA1874002F792120B7a"
```
4. Run the Vigil example script:
```sh
PRIVATE_KEY=0x6e69815c1d0150b18375006f5f4dc2adacef164fd99f56620f452c13f9ebcd57 npx hardhat run --network dev scripts/run-vigil.ts
```

##### ACTUAL RESULTS

After "Checking the secret again" is printed, the `vigil.revealSecret(0)` call fails. This happens even after increasing the timeout.

```
Checking the secret again
Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0x5a2895c11c91a65d4f8eb3e2079fee9b0d6c33db4e6a7418aa1d8b0a9c581dbd", transaction={"hash":"0x5a2895c11c91a65d4f8eb3e2079fee9b0d6c33db4e6a7418aa1d8b0a9c581dbd","type":0,"accessList":null,"blockHash":"0x890a30c256b2b700acd7a06c14d65da51824f06fae9c47bb2baeeb9d399cc8c8","blockNumber":8,"transactionIndex":0,"confirmations":1,"from":"0xBe939A55A64e20a198522DA1874002F792120B7a","gasPrice":{"type":"BigNumber","hex":"0x174876e800"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x174876e800"},"maxFeePerGas":{"type":"BigNumber","hex":"0x174876e800"},"gasLimit":{"type":"BigNumber","hex":"0x989680"},"to":"0xb6B0aD07797e284c057C0D8a28Bc4B98A31Eb0dD","value":{"type":"BigNumber","hex":"0x00"},"nonce":2,"data":"0xa264626f6479a362706b58207a84fc60792215f87647fabcfbbedf4e93c9476e49c08edab746d9610e5305416464617461583c66f7f6d684bc7198ee79d7abfffe62bd56b328304ef35cad33bc9dd501ae39bb140b3b44acc1281e3786d9ff491f99fc28202e60e5a857808e691ee6656e6f6e63654fcd2744d1c780eaf6b9c05522ece88966666f726d617401","r":"0x7f526d01daea388ab09c5925438cab92f540a87dcffb152864ef96ea5b78b5d6","s":"0x6a32f9e4fb5060752294aef9adcdd2373caeb9eaaeffae4f3a33c9a15f7aa836","v":46621,"creates":null,"chainId":23293}, receipt={"to":"0xb6B0aD07797e284c057C0D8a28Bc4B98A31Eb0dD","from":"0xBe939A55A64e20a198522DA1874002F792120B7a","contractAddress":null,"transactionIndex":0,"gasUsed":{"type":"BigNumber","hex":"0x7e89"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x890a30c256b2b700acd7a06c14d65da51824f06fae9c47bb2baeeb9d399cc8c8","transactionHash":"0x5a2895c11c91a65d4f8eb3e2079fee9b0d6c33db4e6a7418aa1d8b0a9c581dbd","logs":[],"blockNumber":8,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x7e89"},"status":0,"type":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (/oasis-project/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/oasis-project/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at EthersProviderWrapper.<anonymous> (/oasis-project/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1549:24)
    at step (/oasis-project/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/oasis-project/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/oasis-project/node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'transaction failed',
  code: 'CALL_EXCEPTION',
  transactionHash: '0x5a2895c11c91a65d4f8eb3e2079fee9b0d6c33db4e6a7418aa1d8b0a9c581dbd',
  transaction: {
    hash: '0x5a2895c11c91a65d4f8eb3e2079fee9b0d6c33db4e6a7418aa1d8b0a9c581dbd',
    type: 0,
    accessList: null,
    blockHash: '0x890a30c256b2b700acd7a06c14d65da51824f06fae9c47bb2baeeb9d399cc8c8',
    blockNumber: 8,
    transactionIndex: 0,
    confirmations: 1,
    from: '0xBe939A55A64e20a198522DA1874002F792120B7a',
    gasPrice: BigNumber { value: "100000000000" },
    maxPriorityFeePerGas: BigNumber { value: "100000000000" },
    maxFeePerGas: BigNumber { value: "100000000000" },
    gasLimit: BigNumber { value: "10000000" },
    to: '0xb6B0aD07797e284c057C0D8a28Bc4B98A31Eb0dD',
    value: BigNumber { value: "0" },
    nonce: 2,
    data: '0xa264626f6479a362706b58207a84fc60792215f87647fabcfbbedf4e93c9476e49c08edab746d9610e5305416464617461583c66f7f6d684bc7198ee79d7abfffe62bd56b328304ef35cad33bc9dd501ae39bb140b3b44acc1281e3786d9ff491f99fc28202e60e5a857808e691ee6656e6f6e63654fcd2744d1c780eaf6b9c05522ece88966666f726d617401',
    r: '0x7f526d01daea388ab09c5925438cab92f540a87dcffb152864ef96ea5b78b5d6',
    s: '0x6a32f9e4fb5060752294aef9adcdd2373caeb9eaaeffae4f3a33c9a15f7aa836',
    v: 46621,
    creates: null,
    chainId: 23293,
    wait: [Function (anonymous)]
  },
  receipt: {
    to: '0xb6B0aD07797e284c057C0D8a28Bc4B98A31Eb0dD',
    from: '0xBe939A55A64e20a198522DA1874002F792120B7a',
    contractAddress: null,
    transactionIndex: 0,
    gasUsed: BigNumber { value: "32393" },
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    blockHash: '0x890a30c256b2b700acd7a06c14d65da51824f06fae9c47bb2baeeb9d399cc8c8',
    transactionHash: '0x5a2895c11c91a65d4f8eb3e2079fee9b0d6c33db4e6a7418aa1d8b0a9c581dbd',
    logs: [],
    blockNumber: 8,
    confirmations: 1,
    cumulativeGasUsed: BigNumber { value: "32393" },
    status: 0,
    type: 0,
    byzantium: true
  }
}

```

##### EXPECTED RESULTS

The example should have revealed the secret:

```
Waiting...
Checking the secret again
The secret ingredient is brussels sprouts
```

**Comment by aefhm** [comment]
This is a great bug report. I can reproduce this locally. Looking more into this now.

**Comment by aefhm** [comment]
@jaa2 thanks for flagging this!

An alternative version of the `run-vigil.ts` script works for me locally where I stuff transactions into the locally running container to ensure that block increments.

```typescript
// Usage: pnpm hardhat run --network <network> scripts/run-vigil.ts

import { ethers } from 'hardhat';

async function main() {
  const Vigil = await ethers.getContractFactory('Vigil');
  const vigil = await Vigil.deploy();
  console.log('Vigil deployed to:', vigil.address);

  const tx = await vigil.createSecret(
    'ingredient',
    30 /* seconds */,
    Buffer.from('brussels sprouts'),
  );
  console.log('Storing a secret in', tx.hash);
  await tx.wait();
  try {
    console.log('Checking the secret');
    await vigil.connect(ethers.provider).callStatic.revealSecret(0);
    console.log('Uh oh. The secret was available!');
    process.exit(1);
  } catch (e: any) {
    console.log('failed to fetch secret:', e.message);
  }
  console.log('Waiting...');

  // Manually stuff transactions to increment local container block
  if (ethers.provider.connection.url.includes('http://127.0.0.1:8545')) {
    console.log('stuff transactions');
    await vigil.revealSecret(0).catch();
    await vigil.revealSecret(0).catch();
    await vigil.revealSecret(0).catch();
    await vigil.revealSecret(0).catch();
    await vigil.revealSecret(0).catch();
    await vigil.revealSecret(0).catch();
    await vigil.revealSecret(0).catch();
    await vigil.revealSecret(0).catch();
    await vigil.revealSecret(0).catch();
  }
  await new Promise((resolve) => setTimeout(resolve, 30_000));
  console.log('Checking the secret again');

  await (await vigil.revealSecret(0)).wait(); // Reveal the secret.
  const secret = await vigil.callStatic.revealSecret(0); // Get the value.
  console.log('The secret ingredient is', Buffer.from(secret.slice(2), 'hex').toString());
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
```

The original script also works fine for me against `testnet`.

I believe the problem is that the timestamp logic assumes a newer block has been created. This is true on a live network (given traffic) but requires more simulation locally.

In #198, we should exercise this test flow and perhaps have a slightly cleaner example 🤔
