### ISSUE TITLE
Fix test flake (signing & verification precompile intermittent error)

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/sapphire-paratime#224]
##### SUMMARY

https://github.com/oasisprotocol/sapphire-paratime/actions/runs/6845602636/job/18611054478

```
  1) Signing
       Ed25519 (Oasis):

      AssertionError: expected true to equal false
      + expected - actual

      -true
      +false
      
      at testSignThenVerify (test/signing.ts:35:7)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Context.<anonymous> (test/signing.ts:131:9)
```

The test verifies that if the message of a signature is changed the verification must fail, however sometimes it returns true. This is very concerning and we need to find how to reproduce this error reliably.

At the moment it happens on maybe 1/50 CI runs and is intermittent - it's not specific to a single signing algorithm.

**Comment by aefhm** [comment]
I think this will be closed by @jberci's recent debugging?

https://github.com/oasisprotocol/sapphire-paratime/blob/ad6ecac38be3e063b345aaa5eb1c68b4b1c7e77f/contracts/test/signing.ts#L26-L36
