### ISSUE TITLE
Web3.js + encrypted transactions

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/sapphire-paratime#247]
As per the Ethers v5 & Ethers v6 standalone tests in https://github.com/oasisprotocol/sapphire-paratime/pull/239

Would like to make sure Web3.js works and the transaction, simulate & estimate calls have encrypted calldata before we can say we officially support Web3.js. As we don't want people to use Sapphire + Web3.js and think it's encrypted but it's not...

The following is a snippet of deploying the TestERC20Token contract, needs to be adapted to work with Web3.js.

```typescript
import { Web3 } from 'web3';
import { TestErc20Token } from "./TestErc20Token.js";
import { assert } from 'console';

async function main () {

    const signer = new Web3('http://127.0.0.1:8545');

    const account = signer.eth.accounts.wallet.add('0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80').get(0)!;
    console.log('account', account.address);

    const contract = new signer.eth.Contract(TestErc20Token.abi, undefined, {
        gasPrice: '100000000000',
        from: account.address
    });

    const deployed = await contract.deploy({
        data: TestErc20Token.bytecode
    }).send({
        gas: '1185560'
    });
    console.log('deployed', deployed.options.address);

    const mintTx = await deployed.methods.mint(account.address, 100n).send();
    console.log('mintTx', mintTx.transactionHash);

    const totalSupply = await deployed.methods.totalSupply().call()
    assert(totalSupply === 100n);
}

await main ();
```

**Comment by CedarMist** [comment]
Currently this fails if you wrap it as follows:

```typescript
const provider = new Web3.providers.HttpProvider('http://127.0.0.1:3000');
const wrappedProvider = wrap(provider);
```

This stems from the following code in `compat.ts`:

```typescript
   const signer = await provider.getSigner();
   const { method, params } = await prepareRequest(args, signer, cipher);
```

This is because we're wrapping a provider without any ability to sign? Even though we add a signer later in the code. Will investigate ways to fully support Web3.js with a local JsonRpcProvider - I expect it *may* work with an injected browser provider.

See the following error:

```
$ pnpm ts-node src/index.ts 
account 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
file:///src/sapphire-paratime/node_modules/.pnpm/ethers@6.9.0/node_modules/ethers/src.ts/utils/errors.ts:687
            error = new TypeError(message);
                    ^
TypeError: invalid address (argument="address", value=null, code=INVALID_ARGUMENT, version=6.9.0)
    at makeError (file:///src/sapphire-paratime/node_modules/.pnpm/ethers@6.9.0/node_modules/ethers/src.ts/utils/errors.ts:687:21)
    at assert (file:///src/sapphire-paratime/node_modules/.pnpm/ethers@6.9.0/node_modules/ethers/src.ts/utils/errors.ts:715:25)
    at assertArgument (file:///src/sapphire-paratime/node_modules/.pnpm/ethers@6.9.0/node_modules/ethers/src.ts/utils/errors.ts:727:5)
    at getAddress (file:///src/sapphire-paratime/node_modules/.pnpm/ethers@6.9.0/node_modules/ethers/src.ts/address/address.ts:121:5)
    at new JsonRpcSigner (file:///src/sapphire-paratime/node_modules/.pnpm/ethers@6.9.0/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:290:19)
    at BrowserProvider.getSigner (file:///src/sapphire-paratime/node_modules/.pnpm/ethers@6.9.0/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:1067:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BrowserProvider.getSigner (file:///src/sapphire-paratime/node_modules/.pnpm/ethers@6.9.0/node_modules/ethers/src.ts/providers/provider-browser.ts:140:16) {
```

**Comment by CedarMist** [comment]
Upon reconsideration we're not going to support Web3.js going forward.
