### ISSUE TITLE
sapphire-py: Bump web3 to 7.x

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/sapphire-paratime#355]
sapphire-py is currently compatible with 6.x version of Web3. Bump it to 7.x and fix any compatibility issues.

**Comment by CedarMist** [comment]
re web3.py 7.x: not many people are using it yet

There are breaking changes from 6.x to 7.x and it's only just been released.

There's no sapphire-py package on PyPi yet, and nobody is using the package apart from Ocean protocol.

If anything, I'd say a compatibility wrapper for Ocean, using the Web3.py version they use, with a function wrapper that means they don't have to build & ship a binary blob for encrypted Sapphire transactions is higher priority.

---

Re: breaking changes

```
======================================================================
ERROR: sapphirepy.tests.test_e2e (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: sapphirepy.tests.test_e2e
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/sapphire-paratime/sapphire-paratime/clients/py/sapphirepy/tests/test_e2e.py", line 9, in <module>
    from web3.middleware import construct_sign_and_send_raw_middleware
ImportError: cannot import name 'construct_sign_and_send_raw_middleware' from 'web3.middleware' (/home/runner/.local/lib/python3.10/site-packages/web3/middleware/__init__.py)
```

**Comment by matevz** [comment]
Fixed in #540
